name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install meson ninja

      - name: Build nova-physics
        run: |
          meson setup build --buildtype=release -Dbuild_examples=false --wipe
          cd build
          meson compile
